CREATE DATABASE twinner;

CREATE TABLE profile(
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE post(
    id SERIAL PRIMARY KEY NOT NULL,
    profile_id INT REFERENCES profile(id) ON DELETE CASCADE,
    content VARCHAR(1000),
    post_date DATE DEFAULT CURRENT_DATE
);

CREATE TABLE comment(
    id SERIAL PRIMARY KEY NOT NULL,
    profile_id INT REFERENCES profile(id) ON DELETE CASCADE,
    post_id INT REFERENCES post(id) ON DELETE CASCADE
);

CREATE TABLE likes (
    id SERIAL PRIMARY KEY NOT NULL,
    profile_id INT REFERENCES profile(id) ON DELETE CASCADE,
    post_id INT REFERENCES post(id) ON DELETE CASCADE
);

CREATE TABLE tag (
    id SERIAL PRIMARY KEY NOT NULL,
    name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE tag_post (
    id SERIAL PRIMARY KEY NOT NULL,
    post_id INT REFERENCES post(id) ON DELETE CASCADE,
    tag_id INT REFERENCES tag(id) ON DELETE CASCADE
);